import traceback
import math
from typing import Any, Dict, Optional
import pandas as pd
import numpy as np


class CodeExecutor:
    """
    Executes dynamically generated Python/Pandas analysis code against a DataFrame
    and extracts the output variable `result` in a JSON-serializable format.
    """

    def __init__(self, default_variable: str = "result"):
        self.default_variable = default_variable

    def execute(self, code: str, df: pd.DataFrame, additional_scope: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """
        Executes Python code with access to DataFrame `df`, pandas `pd`, and numpy `np`.

        :param code: Python code string generated by LLM
        :param df: Target pandas DataFrame
        :param additional_scope: Optional additional variables to inject into execution namespace
        :return: Dict containing execution status, formatted result, result type, or error details
        """
        if not isinstance(df, pd.DataFrame):
            return {
                "status": "error",
                "result": None,
                "result_type": None,
                "error": "Invalid argument: 'df' must be a pandas DataFrame.",
                "traceback": None,
            }

        if not code or not code.strip():
            return {
                "status": "error",
                "result": None,
                "result_type": None,
                "error": "Empty code string provided for execution.",
                "traceback": None,
            }

        # Local execution namespace with df copy to prevent accidental mutation of source data
        execution_globals = {
            "df": df.copy(),
            "pd": pd,
            "np": np,
            "__builtins__": __builtins__,
        }
        if additional_scope:
            execution_globals.update(additional_scope)
        execution_locals = {}

        try:
            # Execute generated code block
            exec(code, execution_globals, execution_locals)

            # Look for target variable in locals first, then globals
            raw_result = execution_locals.get(
                self.default_variable,
                execution_globals.get(self.default_variable)
            )

            if raw_result is None and self.default_variable not in execution_locals and self.default_variable not in execution_globals:
                return {
                    "status": "error",
                    "result": None,
                    "result_type": None,
                    "error": f"Execution completed, but target output variable '{self.default_variable}' was not defined in the code.",
                    "traceback": None,
                }

            result_type = type(raw_result).__name__
            formatted_result = self._sanitize_and_format_result(raw_result)

            return {
                "status": "success",
                "result": formatted_result,
                "result_type": result_type,
                "error": None,
                "traceback": None,
            }

        except Exception as e:
            tb_str = traceback.format_exc()
            return {
                "status": "error",
                "result": None,
                "result_type": None,
                "error": f"{type(e).__name__}: {str(e)}",
                "traceback": tb_str,
            }

    def _sanitize_and_format_result(self, raw_result: Any) -> Any:
        """
        Converts pandas/numpy data types, DataFrames, Series, and special values
        (NaN, Infinity, Timestamps) into pure JSON-serializable Python objects.
        """
        if raw_result is None:
            return None

        # Handle Pandas DataFrame
        if isinstance(raw_result, pd.DataFrame):
            df_reset = raw_result.reset_index() if self._has_named_index(raw_result) else raw_result
            records = df_reset.to_dict(orient="records")
            return self._sanitize_json_values(records)

        # Handle Pandas Series
        if isinstance(raw_result, pd.Series):
            series_name = raw_result.name or "value"
            df_series = raw_result.reset_index()
            # Rename value column if default integer index was reset
            if len(df_series.columns) == 2 and df_series.columns[1] == 0:
                df_series.columns = [df_series.columns[0], series_name]
            records = df_series.to_dict(orient="records")
            return self._sanitize_json_values(records)

        # Handle NumPy arrays
        if isinstance(raw_result, np.ndarray):
            return self._sanitize_json_values(raw_result.tolist())

        # Handle NumPy primitives
        if isinstance(raw_result, (np.integer, np.signedinteger, np.unsignedinteger)):
            return int(raw_result)
        if isinstance(raw_result, (np.floating, np.floating)):
            val = float(raw_result)
            return None if (math.isnan(val) or math.isinf(val)) else val
        if isinstance(raw_result, np.bool_):
            return bool(raw_result)

        # General recursive sanitization for dicts, lists, scalars
        return self._sanitize_json_values(raw_result)

    def _has_named_index(self, df: pd.DataFrame) -> bool:
        """Returns True if the DataFrame index has a non-default name or is MultiIndex."""
        if isinstance(df.index, pd.MultiIndex):
            return True
        return df.index.name is not None

    def _sanitize_json_values(self, obj: Any) -> Any:
        """Recursively cleans NaN, Inf, Timestamps, and NumPy scalars in nested dicts/lists."""
        if isinstance(obj, dict):
            return {str(k): self._sanitize_json_values(v) for k, v in obj.items()}
        elif isinstance(obj, list):
            return [self._sanitize_json_values(item) for item in obj]
        elif isinstance(obj, tuple):
            return [self._sanitize_json_values(item) for item in obj]
        elif isinstance(obj, float):
            return None if (math.isnan(obj) or math.isinf(obj)) else obj
        elif isinstance(obj, (pd.Timestamp, np.datetime64)):
            return str(obj)
        elif pd.isna(obj):
            return None
        elif isinstance(obj, (np.integer, np.signedinteger, np.unsignedinteger)):
            return int(obj)
        elif isinstance(obj, np.floating):
            val = float(obj)
            return None if (math.isnan(val) or math.isinf(val)) else val
        elif isinstance(obj, np.bool_):
            return bool(obj)
        return obj
